[tool.poetry]
name = "tink-homebank-endpoint"
version = "0.0.1"
description = "Pull transactions from Tink and export them in a CSV for Homebank"
authors = ["Jos√© Ignacio Amelivia Santiago <ohcan2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
tink-http-python = "0.0.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pudb = "^2023.1"
codecov = "^2.1.13"
black = "^23.11.0"
pre-commit = "^3.5.0"
mock = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
